//
//  CourseDetailsWorker.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 08.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class CourseDetailsWorker {
    
    private let imageService: ImageManagerProtocol
    private let dataService: DataManagerProtocol
    
    init(imageService: ImageManagerProtocol, dataService: DataManagerProtocol) {
        self.imageService = imageService
        self.dataService = dataService
    }
    
    func getImage(from imageURL: URL?) -> Data? {
        imageService.fetchImageData(from: imageURL)
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        dataService.getFavoriteStatus(for: courseName)
    }
    
    func setFavoriteStatus(for courseName: String, with status: Bool) {
        dataService.setFavoriteStatus(for: courseName, with: status)
    }
}
