//
//  CourseDetailsPresenter.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 08.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsPresentationLogic {
    func presentSomething(response: CourseDetails.ShowCourseDetails.Response)
    func changeIsFavoriteStatus(response: CourseDetails.FavoriteButtonToggle.Response)
}

class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    func changeIsFavoriteStatus(response: CourseDetails.FavoriteButtonToggle.Response) {
        let viewModel = CourseDetails.FavoriteButtonToggle.ViewModel(isFavorite: response.isFavorite)
        viewController?.displayFavoriteButtonStatus(viewModel: viewModel)
    }
    
    weak var viewController: CourseDetailsDisplayLogic?
    
    func presentSomething(response: CourseDetails.ShowCourseDetails.Response) {
        
        let numberOfLessonsLabel = "Number of lessons: \(response.numberOfLessons)"
        let numberOfTestsLabel = "Number of tests: \(response.numberOfTests)"
        let viewModel = CourseDetails.ShowCourseDetails.ViewModel(courseName: response.courseName,
                                                                  numberOfLessons: numberOfLessonsLabel,
                                                                  numberOfTests: numberOfTestsLabel,
                                                                  imageData: response.imageData,
                                                                  isFavorite: response.isFavorite)
        viewController?.displayCourseDetails(viewModel: viewModel)
    }
}
