//
//  CourseDetailsPresenter.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 08.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CourseDetailsPresentationLogic {
    func presentCourseDetails(response: CourseDetails.ShowCourseDetails.Response)
    func presentFavoriteStatus(response: CourseDetails.ChangeFavoriteStatus.Response)
}

class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    
    func presentFavoriteStatus(response: CourseDetails.ChangeFavoriteStatus.Response) {
        let viewModel = CourseDetails.ChangeFavoriteStatus.ViewModel(isFavorite: response.isFavorite)
        viewController?.displayFavoriteButtonStatus(viewModel: viewModel)
    }
    
    weak var viewController: CourseDetailsDisplayLogic?
    
    func presentCourseDetails(response: CourseDetails.ShowCourseDetails.Response) {
        
        let numberOfLessonsLabel = "Number of lessons: \(response.numberOfLessons ?? 0)"
        let numberOfTestsLabel = "Number of tests: \(response.numberOfTests ?? 0)"
        let viewModel = CourseDetails.ShowCourseDetails.ViewModel(courseName: response.courseName ?? "Nil",
                                                                  numberOfLessons: numberOfLessonsLabel,
                                                                  numberOfTests: numberOfTestsLabel,
                                                                  imageData: response.imageData ?? Data(),
                                                                  isFavorite: response.isFavorite)
        viewController?.displayCourseDetails(viewModel: viewModel)
    }
}
