//
//  CoursesListModels.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum CoursesList {
 
    // MARK: Use cases
    enum Something {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
