//
//  CoursesListPresenter.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CoursesListPresentationLogic {
    func presentSomething(response: CoursesList.Something.Response)
}

class CoursesListPresenter: CoursesListPresentationLogic {
    
    weak var viewController: CoursesListDisplayLogic?
    
    func presentSomething(response: CoursesList.Something.Response) {
        let viewModel = CoursesList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
