//
//  CoursesListRouter.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CoursesListRoutingLogic {
    func routeToCourseDetails(segue: UIStoryboardSegue?)
}

protocol CoursesListDataPassing {
    var dataStore: CoursesListDataStore? { get }
}

class CoursesListRouter: NSObject, CoursesListRoutingLogic, CoursesListDataPassing {
    
    weak var viewController: CoursesListViewController?
    var dataStore: CoursesListDataStore?
    
    // MARK: Routing
    
    func routeToCourseDetails(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard let dataStore = dataStore else { return }
            guard let destinationVC = segue.destination as? CourseDetailsViewController else { return }
            guard var destinationDS = destinationVC.router?.dataStore else { return }
            passDataToCourseDetails(source: dataStore, destination: &destinationDS)
        }
        /*else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard let dataStore = dataStore else { return }
            guard let viewController = viewController else { return }
            guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "CourseDetailsViewController") as? CourseDetailsViewController else { return }
            guard var destinationDS = destinationVC.router?.dataStore else { return }
            passDataToCourseDetails(source: dataStore, destination: &destinationDS)
            navigateToCourseDetails(source: viewController, destination: destinationVC)
        } */
    }
    
    // MARK: Navigation
    
    func navigateToCourseDetails(source: CoursesListViewController, destination: CourseDetailsViewController) {
        source.show(destination, sender: nil)
    }
    
    
    // MARK: Passing data
    
    func passDataToCourseDetails(source: CoursesListDataStore, destination: inout CourseDetailsDataStore) {
        if let indexPath = viewController?.tableView.indexPathForSelectedRow {
            destination.course = source.courses[indexPath.row]
        }
    }
}
