//
//  CoursesListInteractor.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CoursesListBusinessLogic {
    func loadCourses()
}

protocol CoursesListDataStore {
    var courses: [Course] { get }
}

class CoursesListInteractor: CoursesListBusinessLogic, CoursesListDataStore {
    var presenter: CoursesListPresentationLogic?
    
    func loadCourses() {
        networkManager.fetchData { [weak self] courses in
            self?.courses = courses
            let response = CoursesList.DisplayCoursesList.Response(courses: courses)
            self?.presenter?.presentCourses(response: response)
        }
    }
    
    var courses: [Course] = []
    
    private let networkManager: NetworkManagerProtocol
    init(networkManager: NetworkManagerProtocol) {
        self.networkManager = networkManager
    }
}
