//
//  CoursesListPresenter.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CoursesListPresentationLogic {
    func presentCourses(response: CoursesList.DisplayCoursesList.Response)
}

class CoursesListPresenter: CoursesListPresentationLogic {
    
    weak var viewController: CoursesListDisplayLogic?
    
    func presentCourses(response: CoursesList.DisplayCoursesList.Response) {
        let rows: [CourseCellViewModelProtocol] = response.courses.map {
            CourseCellViewModel(course: $0)
        }
        let viewModel = CoursesList.DisplayCoursesList.ViewModel(rows: rows)
        viewController?.displayCourses(viewModel: viewModel)
    }
}
