//
//  CoursesListInteractor.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CoursesListBusinessLogic {
    func doSomething(request: CoursesList.Something.Request)
}

protocol CoursesListDataStore {
    
}

class CoursesListInteractor: CoursesListBusinessLogic, CoursesListDataStore {
    
    var presenter: CoursesListPresentationLogic?
    var worker: CoursesListWorker?
    
    func doSomething(request: CoursesList.Something.Request) {
        worker = CoursesListWorker()
        worker?.doSomeWork()
        
        let response = CoursesList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
