//
//  CoursesListModels.swift
//  SwiftbookApp
//
//  Created by Aleksandr Kretov on 10.07.2022.
//  Copyright (c) 2022 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias CourseCellViewModel = CoursesList.DisplayCoursesList.ViewModel.CourseCellViewModel

protocol CourseCellViewModelProtocol {
    var identifier: String { get }
    var height: Double { get }
    var courseName: String { get }
    var imageData: Data? { get }
    init(course: Course)
}

enum CoursesList {
 
    // MARK: Use cases
    enum DisplayCoursesList {
        
        struct Response {
            let courses: [Course]
        }
        
        struct ViewModel {
            struct CourseCellViewModel: CourseCellViewModelProtocol {
                var identifier: String {
                    "CourseCell"
                }
                
                var height: Double {
                    100
                }
                
                var courseName: String {
                    course.name
                }
                
                var imageData: Data? {
                    imageManager.fetchImageData(from: course.imageUrl)
                }
                
                private var course: Course
                private let imageManager: ImageManagerProtocol
                
                init(course: Course) {
                    self.course = course
                    self.imageManager = ImageManager()
                }
            }
            
            let rows: [CourseCellViewModelProtocol]
        }
    }
}
